### ISSUE TITLE
Use Fusion Tables REST API for inserting new raids

### ISSUE THREAD

**Issue by eabedrapo** [chi-immigration-task-force/migra-map#31]
When submitting a raid, the form is using a php file that sends the data to the old mySQL DB.

To avoid returning back to Google Forms that aren't flexible enough we should learn how to send a POST request using Fusion Tables API.

FYI: our data is using Fusion Tables v1 that's deprecated and Google is going to stop support on August 2017, so we have to migrate to v2 sometime in the future. However, the URL for the POST request only changes the version number (from /v1/ into /v2/) so if the migration is too time consuming we may want to use the REST API so the form will work by June 1st and in a second stage (Fall-Winter) make the migration to v2.

Refs:
1. (Fusion Tables API v1) https://developers.google.com/fusiontables/docs/v1/reference/template/insert
2. (Fusion Tables API v2) https://developers.google.com/fusiontables/docs/v2/reference/template/insert

Guide on how to migrate Fusion Tables from v1 into v2: https://developers.google.com/fusiontables/docs/v2/migration_guide

**Comment by guillermokrh** [comment]
The template for our raid.html form: https://developers.google.com/fusiontables/docs/samples/basic_jsonp_request

**Comment by guillermokrh** [comment]
After speaking with some of our mentors from Chi Hack Night, we have decided to use Google Forms, rather than the Google Fusion Table API.
